# Generated by Django 4.1.7 on 2023-03-21 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0004_veiculo_ano"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="modelo",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="veiculo",
                to="garagem.categoria",
            ),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="cor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="veiculo",
                to="garagem.cor",
            ),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="marca",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="veiculo",
                to="garagem.marca",
            ),
        ),
    ]
