# Generated by Django 4.2.4 on 2023-08-22 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("garagem", "0004_itenscompra"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modelo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "modelo",
                "verbose_name_plural": "modelos",
            },
        ),
        migrations.RemoveField(
            model_name="itenscompra",
            name="compra",
        ),
        migrations.RemoveField(
            model_name="itenscompra",
            name="veiculo",
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="marca",
        ),
        migrations.AlterField(
            model_name="acessorio",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="cor",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="marca",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="capa",
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="cor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="veiculos", to="garagem.cor"
            ),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name="Compra",
        ),
        migrations.DeleteModel(
            name="ItensCompra",
        ),
        migrations.AddField(
            model_name="modelo",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="modelo", to="garagem.categoria"
            ),
        ),
        migrations.AddField(
            model_name="modelo",
            name="marca",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="modelo", to="garagem.marca"
            ),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="capa",
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name="+", to="uploader.image"),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="modelo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="veiculos", to="garagem.modelo"
            ),
        ),
    ]
