# Generated by Django 4.2.4 on 2023-08-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("garagem", "0005_modelo_remove_itenscompra_compra_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="descricao",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="acessorios",
            field=models.ManyToManyField(related_name="veiculos", to="garagem.acessorio"),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="capa",
            field=models.ManyToManyField(related_name="+", to="uploader.image"),
        ),
    ]
